name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! Please provide details about your idea.

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see
      placeholder: Describe the feature...
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Explain why this feature would be useful
      placeholder: |
        - Who would benefit from this feature?
        - What problem does it solve?
        - How would you use it?
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How do you think this feature should work?
      placeholder: Describe your proposed implementation...

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other solutions or workarounds have you considered?
      placeholder: Describe alternative solutions you've considered...

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Low (configuration change, small script)
        - Medium (new component, moderate changes)
        - High (major architectural changes)
        - Unknown

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low (nice to have)
        - Medium (would be helpful)
        - High (important for my use case)
        - Critical (blocking my usage)

  - type: checkboxes
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of enhancement is this?
      options:
        - label: New functionality
        - label: Performance improvement
        - label: User interface enhancement
        - label: Documentation improvement
        - label: Hardware compatibility
        - label: Audio processing enhancement
        - label: Configuration option

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information about the feature request
      placeholder: Add any other context, screenshots, or examples here...